- name: Install Jenkins on Ubuntu 18
  hosts: 127.0.0.1
  become: true
  roles:
    - jenkins-ubuntu-18
  vars:
    ansible_host: 127.0.0.1
    ansible_user: ionut-alexandru
    jenkins_version: "2.266"