---
- name: Stop Jenkins service
  systemd:
    name: jenkins
    state: stopped

- name: Disable Jenkins service
  systemd: 
    name: jenkins
    enabled: no

- name: Remove Jenkins package
  apt:
    name: jenkins
    state: absent

- name: Remove Jenkins service file
  file:
    path: /etc/systemd/system/jenkins.service
    state: absent

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes
